### PR TITLE
Fix rapier(x)d-simd-compat to use simd instructions

### LINKED ISSUE #314: rapier2d-simd-compat doesn't really use simd128 instruction
Reproduction:

```bash
wasm-objdump.exe -d ./rapier_wasm2d_bg.wasm | grep :\sfd
```

(0xfd is the prefix of simd opcode)

### PR DESCRIPTION
**Pull request by Vrixyz**
- Fix https://github.com/dimforge/rapier.js/issues/314

- [x] run `cargo clean` to avoid reusing previously compiled crate ; while this doesn't help much with linked issue, I believe that's a sensible thing to do which will avoid surprises in the long run, so I'd argue to keep it, we're not benefitting much from incremental compilation speed if  it comes at a price of sneaky build differences.
- [x] add simd rustflags when building rapier-compat simd -> that's the real fix.
- [x] TODO: add a CI check ; to avoid regressions

### CODE REVIEW

**Comment by Master-Hash** [comment]
I confirm the artifact [here](https://github.com/dimforge/rapier.js/actions/runs/14066143047?pr=315) fixes.

**Comment by Vrixyz** [comment]
> I confirm the artifact [here](https://github.com/dimforge/rapier.js/actions/runs/14066143047?pr=315) fixes.

Thanks for your attention, I'll probably add a verification step in CI, then discuss it with @sebcrozet before we make a new release containing the fix, in the meantime I hope this updated artifact can be useful.

**Comment by Master-Hash** [comment]
I'll use my personal build anyway mdrrrr

File: rapier-compat/build-rust.sh [hunk 1]
```diff
@@ -41,4 +41,10 @@ fi
 
 # Working dir in wasm-pack is the project root so we need that "../../"
 
-wasm-pack build --target web --out-dir "../../rapier-compat/builds/${dimension}d${feature_postfix}/wasm-build" "$rust_source_directory"
+if [[ $feature == "simd" ]]; then
+    export additional_rustflags='-C target-feature=+simd128'
```
Comment (Vrixyz) [inline rapier-compat/build-rust.sh:45]: I tried `export RUSTFLAGS=[...]` but this didn't work, I think my shell expertise is needing an update, there's probably a slightly cleaner way to achieve this.

in the meantime just removing the `export` in the only self-improvement I can come up with.

**Comment by sebcrozet** [comment]
Thanks!
